// 由本机字体文件 name 表自动生成的候选字体清单 (2026-08-11)
// CANDIDATES: 全部名称变体(中/英/PostScript); DISPLAY_NAMES: 别名 -> 首选中文名
// 重新生成: fontTools 扫描 ~/Library/Fonts、/Library/Fonts、/System/Library/Fonts
export const LOCAL_FONT_CANDIDATES: string[] = [
  ".Aqua Kana",
  ".Aqua かな",
  ".SF NS",
  ".SFNS-Regular",
  ".SFNS-RegularItalic",
  "A_KSO 闘龍",
  "A_KsoTouryu",
  "Apple SD Gothic Neo",
  "Apple SD Gothic Neo Regular",
  "Apple SD 산돌고딕 Neo",
  "Apple SD 산돌고딕 Neo 일반체",
  "AppleGothic",
  "AppleGothic Regular",
  "AppleGothic 일반체",
  "AppleMyungjo",
  "AppleMyungjo Regular",
  "AppleMyungjo 일반체",
  "AppleSDGothicNeo-Regular",
  "AquaKana",
  "By JOSSQ-DMF in BeiJing",
  "CookHandStd-R",
  "Czcionka systemowa",
  "Czcionka systemowa Regular Italic",
  "DFHSGothic-W5",
  "DFHSGothic-W5-WIN-RKSJ-H",
  "DFHSMincho-W5",
  "DFHSMincho-W5-WIN-RKSJ-H",
  "DFHannotateW5-GB",
  "DFPHaiBaoW12",
  "DFPHaiBaoW12-GB",
  "DengXian",
  "DengXian Bold",
  "DengXian Light",
  "DengXian Regular",
  "DengXian-Bold",
  "DengXian-Light",
  "Dengxian",
  "Dengxian-Bold",
  "Dengxian-Light",
  "FC-MouhitsuGyosho",
  "FOT-CookHand Std",
  "FOT-CookHand Std R",
  "FOT-クックハンド Std",
  "FOT-クックハンド Std R",
  "FZBSJW--GB1-0",
  "FZBWKSFW--GB1-0",
  "FZBWKSJW--GB1-0",
  "FZBaoSong-Z04S",
  "FZBaoSong-Z04T",
  "FZBeiWeiKaiShu-S19S",
  "FZBeiWeiKaiShu-Z15T",
  "FZCCHFW--GB1-0",
  "FZCCHJW--GB1-0",
  "FZCCHK--GBK1-0",
  "FZCHYFW--GB1-0",
  "FZCHYJW--GB1-0",
  "FZCQFW--GB1-0",
  "FZCQJW--GB1-0",
  "FZCQK--GBK1-0",
  "FZCSFW--GB1-0",
  "FZCSJW--GB1-0",
  "FZCSK--GBK1-0",
  "FZCYFW--GB1-0",
  "FZCYJW--GB1-0",
  "FZCYK--GBK1-0",
  "FZCaiYun-M09",
  "FZCaiYun-M09S",
  "FZCaiYun-M09T",
  "FZChaoCuHei-M10",
  "FZChaoCuHei-M10S",
  "FZChaoCuHei-M10T",
  "FZCuHei-B03T",
  "FZCuHuoYi-M25S",
  "FZCuHuoYi-M25T",
  "FZCuQian-M17",
  "FZCuQian-M17S",
  "FZCuQian-M17T",
  "FZCuSong-B09",
  "FZCuSong-B09S",
  "FZCuSong-B09T",
  "FZCuYuan-M03",
  "FZCuYuan-M03S",
  "FZCuYuan-M03T",
  "FZDBSFW--GB1-0",
  "FZDBSJW--GB1-0",
  "FZDBSK--GBK1-0",
  "FZDHTFW--GB1-0",
  "FZDHTK--GBK1-0",
  "FZDYSK--GBK1-0",
  "FZDaBiaoSong-B06",
  "FZDaBiaoSong-B06S",
  "FZDaBiaoSong-B06T",
  "FZDaHei-B02",
  "FZDaHei-B02T",
  "FZFSFW--GB1-0",
  "FZFSJW--GB1-0",
  "FZFangSong-Z02S",
  "FZFangSong-Z02T",
  "FZGLFW--GB1-0",
  "FZGLJW--GB1-0",
  "FZGuLi-S12S",
  "FZGuLi-S12T",
  "FZH4FW--GB1-0",
  "FZHCJW--GB1-0",
  "FZHCK--GBK1-0",
  "FZHLFW--GB1-0",
  "FZHLJW--GB1-0",
  "FZHLK--GBK1-0",
  "FZHPFW--GB1-0",
  "FZHPJW--GB1-0",
  "FZHPK--GBK1-0",
  "FZHTFW--GB1-0",
  "FZHei-B01T",
  "FZHuPo-M04",
  "FZHuPo-M04S",
  "FZHuPo-M04T",
  "FZHuaLi-M14",
  "FZHuaLi-M14S",
  "FZHuaLi-M14T",
  "FZHuangCao-S09",
  "FZHuangCao-S09S",
  "FZJZFW--GB1-0",
  "FZJZJW--GB1-0",
  "FZJianZhi-M23S",
  "FZJianZhi-M23T",
  "FZKANGFW--GB1-0",
  "FZKANGJW--GB1-0",
  "FZKANGK--GBK1-0",
  "FZKATFW--GB1-0",
  "FZKATJW--GB1-0",
  "FZKTFW--GB1-0",
  "FZKTJW--GB1-0",
  "FZKaTong-M19S",
  "FZKaTong-M19T",
  "FZKai-Z03S",
  "FZKai-Z03T",
  "FZKangTi-S07",
  "FZKangTi-S07S",
  "FZKangTi-S07T",
  "FZL2FW--GB1-0",
  "FZL2JW--GB1-0",
  "FZL2K--GBK1-0",
  "FZLANTY_K--GBK1-0",
  "FZLBFW--GB1-0",
  "FZLBJW--GB1-0",
  "FZLSFW--GB1-0",
  "FZLSJW--GB1-0",
  "FZLSK--GBK1-0",
  "FZLTZHK--GBK1-0",
  "FZLXTFW--GB1-0",
  "FZLXTJW--GB1-0",
  "FZLanTingHei-DB-GBK",
  "FZLanTingYuan-R-GBK",
  "FZLiBian-S02S",
  "FZLiBian-S02T",
  "FZLiShu II-S06",
  "FZLiShu II-S06S",
  "FZLiShu II-S06T",
  "FZLiShu-S01",
  "FZLiShu-S01S",
  "FZLiShu-S01T",
  "FZLiuXingTi-M26S",
  "FZLiuXingTi-M26T",
  "FZMHFW--GB1-0",
  "FZMHJW--GB1-0",
  "FZMHK--GBK1-0",
  "FZMeiHei-M07",
  "FZMeiHei-M07S",
  "FZMeiHei-M07T",
  "FZNBSJW--GB1-0",
  "FZNBSK--GBK1-0",
  "FZNSTFW--GB1-0",
  "FZNSTJW--GB1-0",
  "FZNSTK--GBK1-0",
  "FZNew BaoSong-Z12",
  "FZNew BaoSong-Z12S",
  "FZNew ShuSong-Z10T",
  "FZNew ShuTi-S08",
  "FZNew ShuTi-S08S",
  "FZNew ShuTi-S08T",
  "FZNew XiuLi-Z11T",
  "FZPHFW--GB1-0",
  "FZPHTFW--GB1-0",
  "FZPHTJW--GB1-0",
  "FZPHTK--GBK1-0",
  "FZPTYJW--GB1-0",
  "FZPWFW--GB1-0",
  "FZPWJW--GB1-0",
  "FZPWK--GBK1-0",
  "FZPangTouYu-M24S",
  "FZPangWa-M18",
  "FZPangWa-M18S",
  "FZPangWa-M18T",
  "FZPingHe-S11",
  "FZPingHe-S11S",
  "FZPingHe-S11T",
  "FZPingHei-B04T",
  "FZQTFW--GB1-0",
  "FZQTJW--GB1-0",
  "FZQiTi-S14S",
  "FZQiTi-S14T",
  "FZS3JW--GB1-0",
  "FZS3K--GBK1-0",
  "FZSEFW--GB1-0",
  "FZSEJW--GB1-0",
  "FZSEK--GBK1-0",
  "FZSHFW--GB1-0",
  "FZSHHFW--GB1-0",
  "FZSHHJW--GB1-0",
  "FZSHJW--GB1-0",
  "FZSHK--GBK1-0",
  "FZSJSFW--GB1-0",
  "FZSJSJW--GB1-0",
  "FZSJSK--GBK1-0",
  "FZSSFW--GB1-0",
  "FZSSJW--GB1-0",
  "FZSTFW--GB1-0",
  "FZSTJW--GB1-0",
  "FZSTK--GBK1-0",
  "FZSYFW--GB1-0",
  "FZSYJW--GB1-0",
  "FZSZFW--GB1-0",
  "FZSZJW--GB1-0",
  "FZSZK--GBK1-0",
  "FZShaoEr-M11",
  "FZShaoEr-M11S",
  "FZShaoEr-M11T",
  "FZShouJinShu-S10",
  "FZShouJinShu-S10S",
  "FZShouJinShu-S10T",
  "FZShuSong-Z01S",
  "FZShuSong-Z01T",
  "FZShuTi-S05",
  "FZShuTi-S05S",
  "FZShuTi-S05T",
  "FZShuiHei-M21S",
  "FZShuiHei-M21T",
  "FZShuiZhu-M08",
  "FZShuiZhu-M08S",
  "FZShuiZhu-M08T",
  "FZSong III-Z05",
  "FZSong III-Z05S",
  "FZSongHei-B07",
  "FZSongHei-B07S",
  "FZSongHei-B07T",
  "FZSongYi-Z13S",
  "FZSongYi-Z13T",
  "FZTJLSFW--GB1-0",
  "FZTJLSJW--GB1-0",
  "FZTieJinLiShu-S17S",
  "FZTieJinLiShu-Z14T",
  "FZWBFW--GB1-0",
  "FZWBJW--GB1-0",
  "FZWBK--GBK1-0",
  "FZWeiBei-S03",
  "FZWeiBei-S03S",
  "FZWeiBei-S03T",
  "FZXBSFW--GB1-0",
  "FZXBSJW--GB1-0",
  "FZXDXJW--GB1-0",
  "FZXDXK--GBK1-0",
  "FZXH1FW--GB1-0",
  "FZXH1JW--GB1-0",
  "FZXIANGLFW--GB1-0",
  "FZXIANGLJW--GB1-0",
  "FZXKFW--GB1-0",
  "FZXKJW--GB1-0",
  "FZXKK--GBK1-0",
  "FZXLFW--GB1-0",
  "FZXQFW--GB1-0",
  "FZXQJW--GB1-0",
  "FZXQK--GBK1-0",
  "FZXSHFW--GB1-0",
  "FZXSHJW--GB1-0",
  "FZXSHK--GBK1-0",
  "FZXSSFW--GB1-0",
  "FZXXLFW--GB1-0",
  "FZXZTFW--GB1-0",
  "FZXiDengXian-Z06",
  "FZXiDengXian-Z06S",
  "FZXiHei I-Z08S",
  "FZXiHei I-Z08T",
  "FZXiQian-M15",
  "FZXiQian-M15S",
  "FZXiQian-M15T",
  "FZXiShanHu-M13",
  "FZXiShanHu-M13S",
  "FZXiShanHu-M13T",
  "FZXiYuan-M01S",
  "FZXiYuan-M01T",
  "FZXiangLi-S17S",
  "FZXiangLi-S17T",
  "FZXiaoBiaoSong-B05S",
  "FZXiaoBiaoSong-B05T",
  "FZXiaoZhuanTi-S13T",
  "FZXingKai-S04",
  "FZXingKai-S04S",
  "FZXingKai-S04T",
  "FZY1FW--GB1-0",
  "FZY1JW--GB1-0",
  "FZY3FW--GB1-0",
  "FZY3JW--GB1-0",
  "FZY3K--GBK1-0",
  "FZY4FW--GB1-0",
  "FZY4JW--GB1-0",
  "FZY4K--GBK1-0",
  "FZYBKSFW--GB1-0",
  "FZYBKSJW--GB1-0",
  "FZYBXSFW--GB1-0",
  "FZYBXSJW--GB1-0",
  "FZYHFW--GB1-0",
  "FZYHJW--GB1-0",
  "FZYTFW--GB1-0",
  "FZYTJW--GB1-0",
  "FZYTK--GBK1-0",
  "FZYXFW--GB1-0",
  "FZYXJW--GB1-0",
  "FZYXK--GBK1-0",
  "FZYaSong-EB-GBK",
  "FZYaoTi-M06",
  "FZYaoTi-M06S",
  "FZYaoTi-M06T",
  "FZYiHei-M20S",
  "FZYiHei-M20T",
  "FZYingBiKaiShu-S15S",
  "FZYingBiKaiShu-S15T",
  "FZYingBiXingShu-S16S",
  "FZYingBiXingShu-S16T",
  "FZYouXian-Z09",
  "FZYouXian-Z09S",
  "FZYouXian-Z09T",
  "FZZBHFW--GB1-0",
  "FZZBHJW--GB1-0",
  "FZZCHK--GBK1-0",
  "FZZDXFW--GB1-0",
  "FZZDXJW--GB1-0",
  "FZZHYFW--GB1-0",
  "FZZHYJW--GB1-0",
  "FZZHYK--GBK1-0",
  "FZZKFW--GB1-0",
  "FZZQFW--GB1-0",
  "FZZQJW--GB1-0",
  "FZZQK--GBK1-0",
  "FZZYFW--GB1-0",
  "FZZYJW--GB1-0",
  "FZZYK--GBK1-0",
  "FZZhanBiHei-M22S",
  "FZZhanBiHei-M22T",
  "FZZhengHei-B-GBK",
  "FZZhiYi-M12",
  "FZZhiYi-M12S",
  "FZZhiYi-M12T",
  "FZZhongDengXian-Z07S",
  "FZZhongDengXian-Z07T",
  "FZZhongKai-B08T",
  "FZZhongQian-M16",
  "FZZhongQian-M16S",
  "FZZhongQian-M16T",
  "FZZhunYuan-M02",
  "FZZhunYuan-M02S",
  "FZZhunYuan-M02T",
  "FZZongYi-M05",
  "FZZongYi-M05S",
  "FZZongYi-M05T",
  "FZuanSu",
  "FangSong",
  "FangSong_GB2312",
  "Fashion font,  by www.6763.net",
  "Fashion font, by www.6763.NET",
  "Fashion font, by www.6763.net",
  "Fashion font, made by www.6763.",
  "Fashion font, made by www.6763.net",
  "Fcaili",
  "Fheifangbei",
  "Fliukai",
  "Fluxing",
  "Font Sistem",
  "Font Sistem Italik Biasa",
  "Font Sistem Reguler Cetak Miring",
  "Font de sistem",
  "Font de sistem Normal cursiv",
  "Font di sistema",
  "Font di sistema Regolare corsivo",
  "Font sustava",
  "Font sustava Regular Italic",
  "Fonte do Sistema",
  "Fonte do Sistema Normal Itálico",
  "Fouxing",
  "Ftangli",
  "Fzicao",
  "Fzikai",
  "GJJCQJW--GB1-0",
  "GJJCuQian-M17S",
  "GJJHCJW--GB1-0",
  "GJJHPJW--GB1-0",
  "GJJHuangCao-S09S",
  "GJJSZJW--GB1-0",
  "GJJShuiZhu-M08S",
  "GJJXQJW--GB1-0",
  "GJJXiQian-M15S",
  "GJJZHYJW--GB1-0",
  "GJJZQJW--GB1-0",
  "GJJZhiYi-M12S",
  "GJJZhongQian-M16S",
  "Gen Jyuu Gothic",
  "Gen Jyuu Gothic Regular",
  "GenJyuuGothic-Regular",
  "HYBaiQiJ",
  "HYBaoSongF",
  "HYBaoSongJ",
  "HYCaiDieJ",
  "HYCaiYunF",
  "HYCaiYunJ",
  "HYChangMeiHeiF",
  "HYChangMeiHeiJ",
  "HYChangSongF",
  "HYChangSongJ",
  "HYChangYiF",
  "HYChangYiJ",
  "HYChaoCuHeiF",
  "HYChaoCuHeiJ",
  "HYChaoCuSongF",
  "HYChaoCuSongJ",
  "HYChaoCuYuanJ",
  "HYChenPinJ",
  "HYCuFangSongJ",
  "HYCuHeiF",
  "HYCuHeiJ",
  "HYCuSongF",
  "HYCuSongJ",
  "HYCuYuanF",
  "HYCuYuanJ",
  "HYCuZhuanF",
  "HYDaHeiF",
  "HYDaHeiJ",
  "HYDaLiShuF",
  "HYDaLiShuJ",
  "HYDaSongF",
  "HYDaSongJ",
  "HYDaiYuJ",
  "HYDieYuJ",
  "HYDuDuJ",
  "HYFangDieF",
  "HYFangDieJ",
  "HYFangLiJ",
  "HYFangSongF",
  "HYFangSongJ",
  "HYGanLanF",
  "HYGanLanJ",
  "HYHaHaJ",
  "HYHaiYunJ",
  "HYHeiMiF",
  "HYHeiMiJ",
  "HYHeiQiJ",
  "HYHuPoF",
  "HYHuPoJ",
  "HYHuaDieJ",
  "HYHuoChaiJ",
  "HYJiaShuF",
  "HYJiaShuJ",
  "HYKaiTiF",
  "HYKaiTiJ",
  "HYLiHeiJ",
  "HYLingBoF",
  "HYLingBoJ",
  "HYLingXinJ",
  "HYLuoBoJ",
  "HYManBuF",
  "HYManBuJ",
  "HYMiMiF",
  "HYMiMiJ",
  "HYNanGongJ",
  "HYQingYunJ",
  "HYShenGongJ",
  "HYShouJinShuF",
  "HYShouJinShuJ",
  "HYShuHunJ",
  "HYShuSongErF",
  "HYShuSongErJ",
  "HYShuSongYiF",
  "HYShuSongYiJ",
  "HYShuTongF",
  "HYShuTongJ",
  "HYShuangXianF",
  "HYShuangXianJ",
  "HYShuiBoJ",
  "HYShuiDiF",
  "HYShuiDiJ",
  "HYTaiJiJ",
  "HYTeXiDengXianJ",
  "HYWaWaZhuanJ",
  "HYWeiBeiF",
  "HYWeiBeiJ",
  "HYXiDengXianF",
  "HYXiDengXianJ",
  "HYXiXingKaiJ",
  "HYXiYuanF",
  "HYXiYuanJ",
  "HYXiZhongYuanF",
  "HYXiZhongYuanJ",
  "HYXiaoLiShuF",
  "HYXiaoLiShuJ",
  "HYXingKaiF",
  "HYXingKaiJ",
  "HYXingShiF",
  "HYXingShiJ",
  "HYXiuYingF",
  "HYXiuYingJ",
  "HYXueFengF",
  "HYXueFengJ",
  "HYYaYaJ",
  "HYYanKaiF",
  "HYYanLingJ",
  "HYYuanDieF",
  "HYYuanDieJ",
  "HYZHongSongJ",
  "HYZhongDengXianF",
  "HYZhongDengXianJ",
  "HYZhongHeiF",
  "HYZhongHeiJ",
  "HYZhongKaiJ",
  "HYZhongLiShuF",
  "HYZhongLiShuJ",
  "HYZhongSongF",
  "HYZhongYuanF",
  "HYZhongYuanJ",
  "HYZhuJieF",
  "HYZhuJieJ",
  "HYZhuanShuF",
  "HYZiDianSongF",
  "HYZiDianSongJ",
  "HYZongYiF",
  "HYZongYiJ",
  "HYa0gf",
  "HYa0gj",
  "HYa1gf",
  "HYa1gj",
  "HYa2gf",
  "HYa2gj",
  "HYa3gf",
  "HYa3gj",
  "HYa4gf",
  "HYa4gj",
  "HYa5gf",
  "HYa5gj",
  "HYa6gf",
  "HYa6gj",
  "HYa7gf",
  "HYa7gj",
  "HYa9gf",
  "HYa9gj",
  "HYb0gf",
  "HYb0gj",
  "HYb1gf",
  "HYb1gj",
  "HYb2gf",
  "HYb2gj",
  "HYb3gf",
  "HYb3gj",
  "HYb4gf",
  "HYb4gj",
  "HYb5gf",
  "HYb5gj",
  "HYb6gf",
  "HYb6gj",
  "HYb7gf",
  "HYb7gj",
  "HYb8gf",
  "HYb8gj",
  "HYb9gf",
  "HYb9gj",
  "HYc1gf",
  "HYc1gj",
  "HYc3gj",
  "HYc4gf",
  "HYd1gf",
  "HYd1gj",
  "HYd2gf",
  "HYd2gj",
  "HYd4gj",
  "HYe0gj",
  "HYe1gf",
  "HYe1gj",
  "HYe2gf",
  "HYe2gj",
  "HYe3gf",
  "HYe3gj",
  "HYe4gf",
  "HYe4gj",
  "HYf0gj",
  "HYf1gf",
  "HYf1gj",
  "HYf2gf",
  "HYf2gj",
  "HYf3gf",
  "HYf3gj",
  "HYf4gj",
  "HYf5gj",
  "HYf9gj",
  "HYg1gf",
  "HYg1gj",
  "HYg2gf",
  "HYg2gj",
  "HYg3gj",
  "HYg4gj",
  "HYg6gj",
  "HYh1gf",
  "HYh1gj",
  "HYh2gj",
  "HYh3gj",
  "HYh4gj",
  "HYi1gf",
  "HYi1gj",
  "HYi2gj",
  "HYi3gf",
  "HYi3gj",
  "HYi4gj",
  "HYj1gf",
  "HYj2gj",
  "HYj3gf",
  "HYk1gf",
  "HYk1gj",
  "HYk2gj",
  "HYk3gj",
  "HYk5gj",
  "HYl1gf",
  "HYl1gj",
  "HYm1gf",
  "HYm1gj",
  "HYm2gf",
  "HYm2gj",
  "HYm4gj",
  "HYm5gj",
  "HYm6gj",
  "HYm7gj",
  "HYn1gf",
  "HYn1gj",
  "HYn3gj",
  "HYo1gf",
  "HYo1gj",
  "HYo2gf",
  "HYo2gj",
  "HYo3gj",
  "HYp1gf",
  "HYp1gj",
  "HYq1gf",
  "HYq1gj",
  "HYq2gj",
  "HYr1gf",
  "HYr1gj",
  "HYr2gf",
  "HYr2gj",
  "HYr3gj",
  "HYt4gj",
  "HYx1gf",
  "HYx1gj",
  "HYx4gf",
  "HYy1gf",
  "HYy1gj",
  "HYy2gj",
  "HYy4gj",
  "HakusyuGyosyoPro_kk",
  "HakusyuGyosyo_kk",
  "HakusyuInsoutai_kk",
  "HanWangCC02",
  "HanWangFangSongMedium",
  "HanWangFangSongMedium-Gb5",
  "HanWangGB06",
  "HanWangGSolid06cut1",
  "HanWangHeiHeavy",
  "HanWangKaiBold-Gb5",
  "HanWangKaiMediumChuIn",
  "HanWangKanTan",
  "HanWangMingBlack",
  "HanWangMingHeavy",
  "HanWangMingMedium",
  "HanWangMingMediumPoIn2",
  "HanWangMingMediumPoIn3",
  "HanWangSinSongThin-Gb5",
  "HanWangWCL02",
  "HanWangWCL03",
  "HanWangWCL05",
  "HanWangWCL06",
  "HanWangWCL08",
  "HanWangWCL10",
  "HanWangYenHeavy",
  "Heiti TC",
  "Heiti TC Light",
  "Heiti TC Medium",
  "Heiti-번체",
  "Heiti-번체 가는체",
  "Heiti-번체 중간체",
  "HiraMaruPro-W4",
  "HiraMinProN-W3",
  "Hiragino Maru Gothic Pro",
  "Hiragino Maru Gothic Pro W4",
  "Hiragino Mincho ProN",
  "Hiragino Mincho ProN W3",
  "Hiragino Sans",
  "Hiragino Sans GB",
  "Hiragino Sans GB W3",
  "Hiragino Sans W0",
  "Hiragino Sans W1",
  "Hiragino Sans W2",
  "Hiragino Sans W3",
  "Hiragino Sans W4",
  "Hiragino Sans W5",
  "Hiragino Sans W6",
  "Hiragino Sans W7",
  "Hiragino Sans W8",
  "Hiragino Sans W9",
  "HiraginoSans-W0",
  "HiraginoSans-W1",
  "HiraginoSans-W2",
  "HiraginoSans-W3",
  "HiraginoSans-W4",
  "HiraginoSans-W5",
  "HiraginoSans-W6",
  "HiraginoSans-W7",
  "HiraginoSans-W8",
  "HiraginoSans-W9",
  "HiraginoSansGB-W3",
  "JCaoCuYuan",
  "JChangYi",
  "JChenPinPo",
  "JCuYuan",
  "JDaiYu",
  "JDuDu",
  "JFangLi",
  "JHaHa",
  "JHuaLi",
  "JHuoCai",
  "JKangTi",
  "JLiBian",
  "JLiEr",
  "JLiHei",
  "JLinBo",
  "JLuobo",
  "JManBuTi",
  "JMeiHei",
  "JPangWa",
  "JPinHe",
  "JSaoEr",
  "JShuShong",
  "JShuTi",
  "JSouJingSu",
  "JTeXiDenXian",
  "JWaWAZuan",
  "JXiHei",
  "JXiSanHu",
  "JXiaoLiSu",
  "JXinBaoSong",
  "JXinSuTi",
  "JXiuYing",
  "JXueFeng",
  "JYaYa",
  "JYanLin",
  "JYaoTi",
  "JZhiDianSong",
  "JZuJie",
  "JZunYuan",
  "Jcacuhei",
  "Jcufangsong",
  "Jheiqi",
  "Jquwei",
  "Jtaiji",
  "Järjestelmäfontti",
  "Järjestelmäfontti Normaali kursiivi",
  "KaiTi",
  "MINIJbaiqi",
  "MINIj4gj",
  "MKsoTouryu",
  "Malgun Gothic",
  "Malgun Gothic Bold",
  "Malgun Gothic Semilight",
  "MalgunGothic",
  "MalgunGothic-Semilight",
  "MalgunGothicBold",
  "NanSung-Medium",
  "Phông chữ Hệ thống",
  "Phông chữ Hệ thống Nghiêng Thường",
  "Police système",
  "Police système Courant italique",
  "Rendszerbetűtípus",
  "Rendszerbetűtípus Normál dőlt",
  "RiWenMaoBiXingShu",
  "SCF-9jiangxs",
  "STHeitiTC-Light",
  "STHeitiTC-Medium",
  "STSongti-SC-Black",
  "SimHei",
  "SimSun",
  "Sistem Fontu",
  "Sistem Fontu Normal İtalik",
  "Songti SC",
  "Songti SC Black",
  "Source Han Sans CN",
  "Source Han Sans CN Medium",
  "Source Han Sans JP",
  "Source Han Sans JP Medium",
  "Source Han Sans SC",
  "Source Han Sans TW",
  "Source Han Sans TW Medium",
  "SourceHanSansCN-Medium",
  "SourceHanSansJP-Medium",
  "SourceHanSansSC-Regular",
  "SourceHanSansTW-Medium",
  "Systeemlettertype",
  "Systeemlettertype Regulier cursief",
  "System Font",
  "System Font Regular Italic",
  "Systemfont",
  "Systemfont Normal kursiv",
  "Systemschrift",
  "Systemschrift Regular kursiv",
  "Systemskrift",
  "Systemskrift Normal kursiv",
  "Systemtypsnitt",
  "Systemtypsnitt Normal kursiv",
  "Systémové písmo",
  "Systémové písmo Regular Italic",
  "Tipo de letra del sistema",
  "Tipo de letra del sistema Cursiva regular",
  "Tipo de letra do sistema",
  "Tipo de letra do sistema Regular itálico",
  "Tipus de lletra del sistema",
  "Tipus de lletra del sistema Normal cursiva",
  "WenQuanYi Micro Hei",
  "WenQuanYi Micro Hei Mono",
  "WenQuanYi Zen Hei",
  "WenQuanYi Zen Hei Mono",
  "WenQuanYiMicroHei",
  "WenQuanYiMicroHeiMono",
  "WenQuanYiZenHei",
  "WenQuanYiZenHeiMono",
  "fwangxing",
  "fzukai",
  "not included.",
  "★日文毛笔行书",
  "システムフォント",
  "システムフォント レギュラー・イタリック",
  "ヒラギノ丸ゴ Pro",
  "ヒラギノ丸ゴ Pro W4",
  "ヒラギノ明朝 ProN",
  "ヒラギノ明朝 ProN W3",
  "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック Sans W8",
  "ヒラギノ角ゴシック W0",
  "ヒラギノ角ゴシック W1",
  "ヒラギノ角ゴシック W2",
  "ヒラギノ角ゴシック W3",
  "ヒラギノ角ゴシック W4",
  "ヒラギノ角ゴシック W5",
  "ヒラギノ角ゴシック W6",
  "ヒラギノ角ゴシック W7",
  "ヒラギノ角ゴシック W8",
  "ヒラギノ角ゴシック W9",
  "䡡湄楮札䍓ⵆ潮瑳",
  "书体坊安景臣钢笔行书",
  "书体坊王学勤钢笔行书",
  "书体坊硬笔行书3500",
  "书体坊米芾体",
  "书体坊赵九江钢笔行书",
  "书体坊郭小语钢笔楷体",
  "书体坊雪纯体3500",
  "仿宋",
  "仿宋_GB2312",
  "冬青黑体简体中文",
  "冬青黑体简体中文 W3",
  "冬青黑體簡體中文",
  "冬青黑體簡體中文 W3",
  "刘德华字体叶根友仿版",
  "华康手札体W5",
  "华康海报体W12(P)",
  "叶根友圆趣卡通体",
  "叶根友奥运字体",
  "叶根友毛笔行书",
  "叶根友特楷简体",
  "叶根友特色空心简体终极版",
  "叶根友特色简体升级版",
  "叶根友特隶简体",
  "叶根友疾风草书",
  "叶根友神工体",
  "叶根友空心简体",
  "叶根友签名体",
  "叶根友蚕燕隶书(3500)",
  "叶根友蚕燕隶书(新春版)",
  "叶根友行书繁",
  "叶根友钢笔行书升级版",
  "叶根友非主流手",
  "叶根友风帆特色",
  "宋体",
  "宋体-简",
  "宋体-简 黑体",
  "宋體-簡",
  "宋體-簡 黑體",
  "帅Fashion font, made by www.6763.net",
  "广捷居迷你字库",
  "思源黑体",
  "思源黑体 CN",
  "思源黑体 CN Medium",
  "思源黑體 TW",
  "思源黑體 TW Medium",
  "文泉驛微米黑",
  "文泉驛正黑",
  "文泉驛等寬微米黑",
  "文泉驛等寬正黑",
  "文泉驿微米黑",
  "文泉驿正黑",
  "文泉驿等宽微米黑",
  "文泉驿等宽正黑",
  "方正中倩_GBK",
  "方正中倩简体",
  "方正中倩繁体",
  "方正中楷繁体",
  "方正中等线简体",
  "方正中等线繁体",
  "方正书宋简体",
  "方正书宋繁体",
  "方正仿宋简体",
  "方正仿宋繁体",
  "方正兰亭中黑_GBK",
  "方正兰亭圆_GBK",
  "方正准圆_GBK",
  "方正准圆简体",
  "方正准圆繁体",
  "方正剪纸简体",
  "方正剪纸繁体",
  "方正北魏楷书简体",
  "方正北魏楷书繁体",
  "方正华隶_GBK",
  "方正华隶简体",
  "方正华隶繁体",
  "方正卡通简体",
  "方正卡通繁体",
  "方正古隶简体",
  "方正古隶繁体",
  "方正启体简体",
  "方正启体繁体",
  "方正大标宋_GBK",
  "方正大标宋简体",
  "方正大标宋繁体",
  "方正大雅宋_GBK",
  "方正大黑_GBK",
  "方正大黑繁体",
  "方正姚体_GBK",
  "方正姚体简体",
  "方正姚体繁体",
  "方正宋一简体",
  "方正宋一繁体",
  "方正宋三_GBK",
  "方正宋三简体",
  "方正宋黑_GBK",
  "方正宋黑简体",
  "方正宋黑繁体",
  "方正小标宋简体",
  "方正小标宋繁体",
  "方正小篆体",
  "方正少儿_GBK",
  "方正少儿简体",
  "方正少儿繁体",
  "方正平和_GBK",
  "方正平和简体",
  "方正平和繁体",
  "方正平黑繁体",
  "方正幼线_GBK",
  "方正幼线简体",
  "方正幼线繁体",
  "方正康体_GBK",
  "方正康体简体",
  "方正康体繁体",
  "方正彩云_GBK",
  "方正彩云简体",
  "方正彩云繁体",
  "方正报宋简体",
  "方正报宋繁体",
  "方正新书宋繁体",
  "方正新报宋_GBK",
  "方正新报宋简体",
  "方正新秀丽繁体",
  "方正新舒体_GBK",
  "方正新舒体简体",
  "方正新舒体繁体",
  "方正楷体简体",
  "方正楷体繁体",
  "方正正粗黑_GBK",
  "方正毡笔黑简体",
  "方正毡笔黑繁体",
  "方正水柱_GBK",
  "方正水柱简体",
  "方正水柱繁体",
  "方正水黑简体",
  "方正水黑繁体",
  "方正流行体简体",
  "方正流行体繁体",
  "方正琥珀_GBK",
  "方正琥珀简体",
  "方正琥珀繁体",
  "方正瘦金书_GBK",
  "方正瘦金书简体",
  "方正瘦金书繁体",
  "方正硬笔楷书简体",
  "方正硬笔楷书繁体",
  "方正硬笔行书简体",
  "方正硬笔行书繁体",
  "方正祥隶简体",
  "方正祥隶繁体",
  "方正稚艺_GBK",
  "方正稚艺简体",
  "方正稚艺繁体",
  "方正粗倩_GBK",
  "方正粗倩简体",
  "方正粗倩繁体",
  "方正粗圆_GBK",
  "方正粗圆简体",
  "方正粗圆繁体",
  "方正粗宋_GBK",
  "方正粗宋简体",
  "方正粗宋繁体",
  "方正粗活意简体",
  "方正粗活意繁体",
  "方正粗黑繁体",
  "方正细倩_GBK",
  "方正细倩简体",
  "方正细倩繁体",
  "方正细圆简体",
  "方正细圆繁体",
  "方正细珊瑚_GBK",
  "方正细珊瑚简体",
  "方正细珊瑚繁体",
  "方正细等线_GBK",
  "方正细等线简体",
  "方正细黑一简体",
  "方正细黑一繁体",
  "方正综艺_GBK",
  "方正综艺简体",
  "方正综艺繁体",
  "方正美黑_GBK",
  "方正美黑简体",
  "方正美黑繁体",
  "方正胖头鱼简体",
  "方正胖娃_GBK",
  "方正胖娃简体",
  "方正胖娃繁体",
  "方正舒体_GBK",
  "方正舒体简体",
  "方正舒体繁体",
  "方正艺黑简体",
  "方正艺黑繁体",
  "方正行楷_GBK",
  "方正行楷简体",
  "方正行楷繁体",
  "方正超粗黑_GBK",
  "方正超粗黑简体",
  "方正超粗黑繁体",
  "方正铁筋隶书简体",
  "方正铁筋隶书繁体",
  "方正隶书_GBK",
  "方正隶书简体",
  "方正隶书繁体",
  "方正隶二_GBK",
  "方正隶二简体",
  "方正隶二繁体",
  "方正隶变简体",
  "方正隶变繁体",
  "方正魏碑_GBK",
  "方正魏碑简体",
  "方正魏碑繁体",
  "方正黄草_GBK",
  "方正黄草简体",
  "方正黑体繁体",
  "时装三维体,《做字网》定做下载..",
  "时装三维体,《做字网》定做下载....",
  "时装分块体,《做字网》定做下载..",
  "时装分块体,《做字网》定做下载....",
  "时装变化体,<做字网>更多下载....",
  "时装圆球体〖做字网〗定做",
  "时装字中字,《做字网》定做下载..",
  "时装字中字,《做字网》定做下载....",
  "时装小立体,《做字网》定做下载..",
  "时装小立体,《做字网》定做下载....",
  "时装扭动体,《做字网》定做下载..",
  "时装扭动体,《做字网》定做下载....",
  "时装扭曲体,《做字网》定做下载..",
  "时装扭曲体,《做字网》定做下载....",
  "时装描边体,《做字网》定做下载..",
  "时装描边体,《做字网》定做下载....",
  "时装揪心体,《做字网》定做下载..",
  "时装揪心体,《做字网》定做下载....",
  "时装斑马魏《做字网》更多下载...",
  "时装斑马魏《做字网》更多下载....",
  "时装歪歪体《做字网》定做下载...",
  "时装歪歪体《做字网》定做下载....",
  "时装残破体《做字网》定做下载...",
  "时装残破体《做字网》定做下载....",
  "时装滚边体,《做字网》定做下载..",
  "时装滚边体,《做字网》定做下载....",
  "时装碎石体《做字网》定做下载...",
  "时装碎石体《做字网》定做下载....",
  "时装空心体,《做字网》定做下载..",
  "时装空心体,《做字网》定做下载....",
  "时装虫蚀体《做字网》定做下载...",
  "时装虫蚀体《做字网》定做下载....",
  "时装蚂蚁体,《做字网》定做下载..",
  "时装蚂蚁体,《做字网》定做下载....",
  "时装蟒纹体《做字网》定做下载...",
  "时装蟒纹体《做字网》定做下载....",
  "时装褶皱体,《做字网》定做下载..",
  "时装褶皱体,《做字网》定做下载....",
  "杪橣捯洭䍓ⵆ潮瑳",
  "楷体",
  "汉仪丫丫体简",
  "汉仪中圆简",
  "汉仪中圆繁",
  "汉仪中宋简",
  "汉仪中宋繁",
  "汉仪中楷简",
  "汉仪中等线简",
  "汉仪中等线繁",
  "汉仪中隶书简",
  "汉仪中隶书繁",
  "汉仪中黑简",
  "汉仪中黑繁",
  "汉仪书宋一简",
  "汉仪书宋一繁",
  "汉仪书宋二简",
  "汉仪书宋二繁",
  "汉仪书魂体简",
  "汉仪仿宋简",
  "汉仪仿宋繁",
  "汉仪凌波体简",
  "汉仪凌波体繁",
  "汉仪南宫体简",
  "汉仪双线体简",
  "汉仪双线体繁",
  "汉仪咪咪体简",
  "汉仪咪咪体繁",
  "汉仪哈哈体简",
  "汉仪嘟嘟体简",
  "汉仪圆叠体简",
  "汉仪圆叠体繁",
  "汉仪大宋简",
  "汉仪大宋繁",
  "汉仪大隶书简",
  "汉仪大隶书繁",
  "汉仪大黑简",
  "汉仪大黑繁",
  "汉仪太极体简",
  "汉仪娃娃篆简",
  "汉仪字典宋简",
  "汉仪字典宋繁",
  "汉仪家书简",
  "汉仪家书繁",
  "汉仪小隶书简",
  "汉仪小隶书繁",
  "汉仪彩云体简",
  "汉仪彩云体繁",
  "汉仪彩蝶体简",
  "汉仪报宋简",
  "汉仪报宋繁",
  "汉仪方叠体简",
  "汉仪方叠体繁",
  "汉仪方隶简",
  "汉仪楷体简",
  "汉仪楷体繁",
  "汉仪橄榄体简",
  "汉仪橄榄体繁",
  "汉仪水波体简",
  "汉仪水滴体简",
  "汉仪水滴体繁",
  "汉仪海韵体简",
  "汉仪清韵体简",
  "汉仪漫步体简",
  "汉仪漫步体繁",
  "汉仪火柴体简",
  "汉仪特细等线简",
  "汉仪琥珀体简",
  "汉仪琥珀体繁",
  "汉仪瘦金书简",
  "汉仪瘦金书繁",
  "汉仪白棋体简",
  "汉仪神工体简",
  "汉仪秀英体简",
  "汉仪秀英体繁",
  "汉仪立黑简",
  "汉仪竹节体简",
  "汉仪竹节体繁",
  "汉仪篆书繁",
  "汉仪粗仿宋简",
  "汉仪粗圆简",
  "汉仪粗圆繁",
  "汉仪粗宋简",
  "汉仪粗宋繁",
  "汉仪粗篆繁",
  "汉仪粗黑简",
  "汉仪粗黑繁",
  "汉仪细中圆简",
  "汉仪细中圆繁",
  "汉仪细圆简",
  "汉仪细圆繁",
  "汉仪细等线简",
  "汉仪细等线繁",
  "汉仪细行楷简",
  "汉仪综艺体简",
  "汉仪综艺体繁",
  "汉仪舒同体简",
  "汉仪舒同体繁",
  "汉仪花蝶体简",
  "汉仪菱心体简",
  "汉仪萝卜体简",
  "汉仪蝶语体简",
  "汉仪行楷简",
  "汉仪行楷繁",
  "汉仪超粗圆简",
  "汉仪超粗宋简",
  "汉仪超粗宋繁",
  "汉仪超粗黑简",
  "汉仪超粗黑繁",
  "汉仪醒示体简",
  "汉仪醒示体繁",
  "汉仪长宋简",
  "汉仪长宋繁",
  "汉仪长美黑简",
  "汉仪长美黑繁",
  "汉仪长艺体简",
  "汉仪长艺体繁",
  "汉仪陈频破体简",
  "汉仪雁翎体简",
  "汉仪雪峰体简",
  "汉仪雪峰体繁",
  "汉仪颜楷繁",
  "汉仪魏碑简",
  "汉仪魏碑繁",
  "汉仪黑咪体简",
  "汉仪黑咪体繁",
  "汉仪黑棋体简",
  "汉仪黛玉体简",
  "源ノ角ゴシック JP",
  "源ノ角ゴシック JP Medium",
  "源柔ゴシック",
  "源柔ゴシック Regular",
  "王汉宗中仿宋简",
  "王汉宗粗楷体简",
  "王汉宗细新宋简",
  "王漢宗中仿宋簡",
  "王漢宗中仿宋繁",
  "王漢宗中明體破音三",
  "王漢宗中明體破音二",
  "王漢宗中明體繁",
  "王漢宗中楷體注音",
  "王漢宗仿宋體一標準",
  "王漢宗勘亭流繁",
  "王漢宗標楷體一空心",
  "王漢宗波卡體一空陰",
  "王漢宗海報體一半天水",
  "王漢宗特圓體繁",
  "王漢宗特明體一標準",
  "王漢宗特明體繁",
  "王漢宗特黑體繁",
  "王漢宗粗楷體簡",
  "王漢宗粗黑體一實陰",
  "王漢宗細新宋簡",
  "王漢宗超明體繁",
  "王漢宗超黑體俏皮動物一",
  "王漢宗酷儷海報",
  "王漢宗鋼筆行楷繁",
  "白舟印相体教漢",
  "白舟行書Pro教漢",
  "白舟行書教漢",
  "章草",
  "等线",
  "等线 Bold",
  "等线 Light",
  "系統字體",
  "系統字體 標準斜體",
  "系统字体",
  "系统字体 常规斜体",
  "草檀斋毛泽东字体",
  "超研澤中仿",
  "迷你简丫丫",
  "迷你简中倩",
  "迷你简书宋",
  "迷你简准圆",
  "迷你简凌波",
  "迷你简华隶",
  "迷你简哈哈",
  "迷你简嘟嘟体",
  "迷你简太极",
  "迷你简姚体",
  "迷你简娃娃篆",
  "迷你简字典宋",
  "迷你简小隶书",
  "迷你简少儿",
  "迷你简平和",
  "迷你简康体",
  "迷你简彩蝶",
  "迷你简新报宋",
  "迷你简新舒体",
  "迷你简方隶",
  "迷你简柏青",
  "迷你简楷体",
  "迷你简楷体_GB2312",
  "迷你简水柱",
  "迷你简水波",
  "迷你简水滴",
  "迷你简汉真广标",
  "迷你简海韵",
  "迷你简清韵",
  "迷你简漫步",
  "迷你简火柴",
  "迷你简特细等线",
  "迷你简琥珀",
  "迷你简瘦金书",
  "迷你简白棋",
  "迷你简秀英",
  "迷你简稚艺",
  "迷你简立黑",
  "迷你简竹节",
  "迷你简粗仿宋",
  "迷你简粗倩",
  "迷你简粗圆",
  "迷你简细倩",
  "迷你简细珊瑚",
  "迷你简细黑",
  "迷你简美黑",
  "迷你简胖娃",
  "迷你简舒体",
  "迷你简花蝶",
  "迷你简萝卜",
  "迷你简蝶语",
  "迷你简超粗圆",
  "迷你简超粗黑",
  "迷你简趣味",
  "迷你简长艺",
  "迷你简陈频破",
  "迷你简隶二",
  "迷你简隶变",
  "迷你简雁翎",
  "迷你简雪君",
  "迷你简雪峰",
  "迷你简黄草",
  "迷你简黑棋",
  "迷你简黛玉",
  "迷你繁唐隶",
  "迷你繁智楷",
  "迷你繁智草",
  "迷你繁曹隶",
  "迷你繁柳楷",
  "迷你繁欧行",
  "迷你繁王行",
  "迷你繁篆书",
  "迷你繁衡方碑",
  "迷你繁褚楷",
  "迷你繁赵楷",
  "迷你繁陆行",
  "金文大篆体",
  "黑体",
  "黑体-繁",
  "黑体-繁 中等",
  "黑体-繁 细体",
  "黑體-繁",
  "黑體-繁 中黑",
  "黑體-繁 細體",
  "黒体-繁",
  "黒体-繁 ミディアム",
  "黒体-繁 ライト",
  "맑은 고딕",
  "맑은 고딕 Bold",
  "맑은 고딕 Semilight",
  "시스템 서체",
  "시스템 서체 일반 이탤릭체",
  "ＤＦ平成ゴシック体W5",
  "ＤＦ平成明朝体W5",
]

export const LOCAL_FONT_DISPLAY_NAMES: Record<string, string> = {
  ".Aqua Kana": ".Aqua かな",
  ".SF NS": "系统字体",
  ".SFNS-Regular": "系统字体",
  ".SFNS-RegularItalic": "系统字体",
  "A_KsoTouryu": "A_KSO 闘龍",
  "Apple SD Gothic Neo": "Apple SD 산돌고딕 Neo",
  "Apple SD Gothic Neo Regular": "Apple SD 산돌고딕 Neo",
  "Apple SD 산돌고딕 Neo 일반체": "Apple SD 산돌고딕 Neo",
  "AppleSDGothicNeo-Regular": "Apple SD 산돌고딕 Neo",
  "AquaKana": ".Aqua かな",
  "By JOSSQ-DMF in BeiJing": "䡡湄楮札䍓ⵆ潮瑳",
  "CookHandStd-R": "FOT-クックハンド Std",
  "Czcionka systemowa": "系统字体",
  "Czcionka systemowa Regular Italic": "系统字体",
  "DFHSGothic-W5": "ＤＦ平成ゴシック体W5",
  "DFHSGothic-W5-WIN-RKSJ-H": "ＤＦ平成ゴシック体W5",
  "DFHSMincho-W5": "ＤＦ平成明朝体W5",
  "DFHSMincho-W5-WIN-RKSJ-H": "ＤＦ平成明朝体W5",
  "DFHannotateW5-GB": "华康手札体W5",
  "DFPHaiBaoW12": "华康海报体W12(P)",
  "DFPHaiBaoW12-GB": "华康海报体W12(P)",
  "DengXian": "等线 Light",
  "DengXian Bold": "等线",
  "DengXian Light": "等线 Light",
  "DengXian Regular": "等线",
  "DengXian-Bold": "等线",
  "DengXian-Light": "等线 Light",
  "Dengxian": "等线",
  "Dengxian-Bold": "等线",
  "Dengxian-Light": "等线 Light",
  "FC-MouhitsuGyosho": "★日文毛笔行书",
  "FOT-CookHand Std": "FOT-クックハンド Std",
  "FOT-CookHand Std R": "FOT-クックハンド Std",
  "FOT-クックハンド Std R": "FOT-クックハンド Std",
  "FZBSJW--GB1-0": "方正报宋简体",
  "FZBWKSFW--GB1-0": "方正北魏楷书繁体",
  "FZBWKSJW--GB1-0": "方正北魏楷书简体",
  "FZBaoSong-Z04S": "方正报宋简体",
  "FZBaoSong-Z04T": "方正报宋繁体",
  "FZBeiWeiKaiShu-S19S": "方正北魏楷书简体",
  "FZBeiWeiKaiShu-Z15T": "方正北魏楷书繁体",
  "FZCCHFW--GB1-0": "方正超粗黑繁体",
  "FZCCHJW--GB1-0": "方正超粗黑简体",
  "FZCCHK--GBK1-0": "方正超粗黑_GBK",
  "FZCHYFW--GB1-0": "方正粗活意繁体",
  "FZCHYJW--GB1-0": "方正粗活意简体",
  "FZCQFW--GB1-0": "方正粗倩繁体",
  "FZCQJW--GB1-0": "方正粗倩简体",
  "FZCQK--GBK1-0": "方正粗倩_GBK",
  "FZCSFW--GB1-0": "方正粗宋繁体",
  "FZCSJW--GB1-0": "方正粗宋简体",
  "FZCSK--GBK1-0": "方正粗宋_GBK",
  "FZCYFW--GB1-0": "方正彩云繁体",
  "FZCYJW--GB1-0": "方正彩云简体",
  "FZCYK--GBK1-0": "方正彩云_GBK",
  "FZCaiYun-M09": "方正彩云_GBK",
  "FZCaiYun-M09S": "方正彩云简体",
  "FZCaiYun-M09T": "方正彩云繁体",
  "FZChaoCuHei-M10": "方正超粗黑_GBK",
  "FZChaoCuHei-M10S": "方正超粗黑简体",
  "FZChaoCuHei-M10T": "方正超粗黑繁体",
  "FZCuHei-B03T": "方正粗黑繁体",
  "FZCuHuoYi-M25S": "方正粗活意简体",
  "FZCuHuoYi-M25T": "方正粗活意繁体",
  "FZCuQian-M17": "方正粗倩_GBK",
  "FZCuQian-M17S": "方正粗倩简体",
  "FZCuQian-M17T": "方正粗倩繁体",
  "FZCuSong-B09": "方正粗宋_GBK",
  "FZCuSong-B09S": "方正粗宋简体",
  "FZCuSong-B09T": "方正粗宋繁体",
  "FZCuYuan-M03": "方正粗圆_GBK",
  "FZCuYuan-M03S": "方正粗圆简体",
  "FZCuYuan-M03T": "方正粗圆繁体",
  "FZDBSFW--GB1-0": "方正大标宋繁体",
  "FZDBSJW--GB1-0": "方正大标宋简体",
  "FZDBSK--GBK1-0": "方正大标宋_GBK",
  "FZDHTFW--GB1-0": "方正大黑繁体",
  "FZDHTK--GBK1-0": "方正大黑_GBK",
  "FZDYSK--GBK1-0": "方正大雅宋_GBK",
  "FZDaBiaoSong-B06": "方正大标宋_GBK",
  "FZDaBiaoSong-B06S": "方正大标宋简体",
  "FZDaBiaoSong-B06T": "方正大标宋繁体",
  "FZDaHei-B02": "方正大黑_GBK",
  "FZDaHei-B02T": "方正大黑繁体",
  "FZFSFW--GB1-0": "方正仿宋繁体",
  "FZFSJW--GB1-0": "方正仿宋简体",
  "FZFangSong-Z02S": "方正仿宋简体",
  "FZFangSong-Z02T": "方正仿宋繁体",
  "FZGLFW--GB1-0": "方正古隶繁体",
  "FZGLJW--GB1-0": "方正古隶简体",
  "FZGuLi-S12S": "方正古隶简体",
  "FZGuLi-S12T": "方正古隶繁体",
  "FZH4FW--GB1-0": "方正粗黑繁体",
  "FZHCJW--GB1-0": "方正黄草简体",
  "FZHCK--GBK1-0": "方正黄草_GBK",
  "FZHLFW--GB1-0": "方正华隶繁体",
  "FZHLJW--GB1-0": "方正华隶简体",
  "FZHLK--GBK1-0": "方正华隶_GBK",
  "FZHPFW--GB1-0": "方正琥珀繁体",
  "FZHPJW--GB1-0": "方正琥珀简体",
  "FZHPK--GBK1-0": "方正琥珀_GBK",
  "FZHTFW--GB1-0": "方正黑体繁体",
  "FZHei-B01T": "方正黑体繁体",
  "FZHuPo-M04": "方正琥珀_GBK",
  "FZHuPo-M04S": "方正琥珀简体",
  "FZHuPo-M04T": "方正琥珀繁体",
  "FZHuaLi-M14": "方正华隶_GBK",
  "FZHuaLi-M14S": "方正华隶简体",
  "FZHuaLi-M14T": "方正华隶繁体",
  "FZHuangCao-S09": "方正黄草_GBK",
  "FZHuangCao-S09S": "方正黄草简体",
  "FZJZFW--GB1-0": "方正剪纸繁体",
  "FZJZJW--GB1-0": "方正剪纸简体",
  "FZJianZhi-M23S": "方正剪纸简体",
  "FZJianZhi-M23T": "方正剪纸繁体",
  "FZKANGFW--GB1-0": "方正康体繁体",
  "FZKANGJW--GB1-0": "方正康体简体",
  "FZKANGK--GBK1-0": "方正康体_GBK",
  "FZKATFW--GB1-0": "方正卡通繁体",
  "FZKATJW--GB1-0": "方正卡通简体",
  "FZKTFW--GB1-0": "方正楷体繁体",
  "FZKTJW--GB1-0": "方正楷体简体",
  "FZKaTong-M19S": "方正卡通简体",
  "FZKaTong-M19T": "方正卡通繁体",
  "FZKai-Z03S": "方正楷体简体",
  "FZKai-Z03T": "方正楷体繁体",
  "FZKangTi-S07": "方正康体_GBK",
  "FZKangTi-S07S": "方正康体简体",
  "FZKangTi-S07T": "方正康体繁体",
  "FZL2FW--GB1-0": "方正隶二繁体",
  "FZL2JW--GB1-0": "方正隶二简体",
  "FZL2K--GBK1-0": "方正隶二_GBK",
  "FZLANTY_K--GBK1-0": "方正兰亭圆_GBK",
  "FZLBFW--GB1-0": "方正隶变繁体",
  "FZLBJW--GB1-0": "方正隶变简体",
  "FZLSFW--GB1-0": "方正隶书繁体",
  "FZLSJW--GB1-0": "方正隶书简体",
  "FZLSK--GBK1-0": "方正隶书_GBK",
  "FZLTZHK--GBK1-0": "方正兰亭中黑_GBK",
  "FZLXTFW--GB1-0": "方正流行体繁体",
  "FZLXTJW--GB1-0": "方正流行体简体",
  "FZLanTingHei-DB-GBK": "方正兰亭中黑_GBK",
  "FZLanTingYuan-R-GBK": "方正兰亭圆_GBK",
  "FZLiBian-S02S": "方正隶变简体",
  "FZLiBian-S02T": "方正隶变繁体",
  "FZLiShu II-S06": "方正隶二_GBK",
  "FZLiShu II-S06S": "方正隶二简体",
  "FZLiShu II-S06T": "方正隶二繁体",
  "FZLiShu-S01": "方正隶书_GBK",
  "FZLiShu-S01S": "方正隶书简体",
  "FZLiShu-S01T": "方正隶书繁体",
  "FZLiuXingTi-M26S": "方正流行体简体",
  "FZLiuXingTi-M26T": "方正流行体繁体",
  "FZMHFW--GB1-0": "方正美黑繁体",
  "FZMHJW--GB1-0": "方正美黑简体",
  "FZMHK--GBK1-0": "方正美黑_GBK",
  "FZMeiHei-M07": "方正美黑_GBK",
  "FZMeiHei-M07S": "方正美黑简体",
  "FZMeiHei-M07T": "方正美黑繁体",
  "FZNBSJW--GB1-0": "方正新报宋简体",
  "FZNBSK--GBK1-0": "方正新报宋_GBK",
  "FZNSTFW--GB1-0": "方正新舒体繁体",
  "FZNSTJW--GB1-0": "方正新舒体简体",
  "FZNSTK--GBK1-0": "方正新舒体_GBK",
  "FZNew BaoSong-Z12": "方正新报宋_GBK",
  "FZNew BaoSong-Z12S": "方正新报宋简体",
  "FZNew ShuSong-Z10T": "方正新书宋繁体",
  "FZNew ShuTi-S08": "方正新舒体_GBK",
  "FZNew ShuTi-S08S": "方正新舒体简体",
  "FZNew ShuTi-S08T": "方正新舒体繁体",
  "FZNew XiuLi-Z11T": "方正新秀丽繁体",
  "FZPHFW--GB1-0": "方正平黑繁体",
  "FZPHTFW--GB1-0": "方正平和繁体",
  "FZPHTJW--GB1-0": "方正平和简体",
  "FZPHTK--GBK1-0": "方正平和_GBK",
  "FZPTYJW--GB1-0": "方正胖头鱼简体",
  "FZPWFW--GB1-0": "方正胖娃繁体",
  "FZPWJW--GB1-0": "方正胖娃简体",
  "FZPWK--GBK1-0": "方正胖娃_GBK",
  "FZPangTouYu-M24S": "方正胖头鱼简体",
  "FZPangWa-M18": "方正胖娃_GBK",
  "FZPangWa-M18S": "方正胖娃简体",
  "FZPangWa-M18T": "方正胖娃繁体",
  "FZPingHe-S11": "方正平和_GBK",
  "FZPingHe-S11S": "方正平和简体",
  "FZPingHe-S11T": "方正平和繁体",
  "FZPingHei-B04T": "方正平黑繁体",
  "FZQTFW--GB1-0": "方正启体繁体",
  "FZQTJW--GB1-0": "方正启体简体",
  "FZQiTi-S14S": "方正启体简体",
  "FZQiTi-S14T": "方正启体繁体",
  "FZS3JW--GB1-0": "方正宋三简体",
  "FZS3K--GBK1-0": "方正宋三_GBK",
  "FZSEFW--GB1-0": "方正少儿繁体",
  "FZSEJW--GB1-0": "方正少儿简体",
  "FZSEK--GBK1-0": "方正少儿_GBK",
  "FZSHFW--GB1-0": "方正宋黑繁体",
  "FZSHHFW--GB1-0": "方正水黑繁体",
  "FZSHHJW--GB1-0": "方正水黑简体",
  "FZSHJW--GB1-0": "方正宋黑简体",
  "FZSHK--GBK1-0": "方正宋黑_GBK",
  "FZSJSFW--GB1-0": "方正瘦金书繁体",
  "FZSJSJW--GB1-0": "方正瘦金书简体",
  "FZSJSK--GBK1-0": "方正瘦金书_GBK",
  "FZSSFW--GB1-0": "方正书宋繁体",
  "FZSSJW--GB1-0": "方正书宋简体",
  "FZSTFW--GB1-0": "方正舒体繁体",
  "FZSTJW--GB1-0": "方正舒体简体",
  "FZSTK--GBK1-0": "方正舒体_GBK",
  "FZSYFW--GB1-0": "方正宋一繁体",
  "FZSYJW--GB1-0": "方正宋一简体",
  "FZSZFW--GB1-0": "方正水柱繁体",
  "FZSZJW--GB1-0": "方正水柱简体",
  "FZSZK--GBK1-0": "方正水柱_GBK",
  "FZShaoEr-M11": "方正少儿_GBK",
  "FZShaoEr-M11S": "方正少儿简体",
  "FZShaoEr-M11T": "方正少儿繁体",
  "FZShouJinShu-S10": "方正瘦金书_GBK",
  "FZShouJinShu-S10S": "方正瘦金书简体",
  "FZShouJinShu-S10T": "方正瘦金书繁体",
  "FZShuSong-Z01S": "方正书宋简体",
  "FZShuSong-Z01T": "方正书宋繁体",
  "FZShuTi-S05": "方正舒体_GBK",
  "FZShuTi-S05S": "方正舒体简体",
  "FZShuTi-S05T": "方正舒体繁体",
  "FZShuiHei-M21S": "方正水黑简体",
  "FZShuiHei-M21T": "方正水黑繁体",
  "FZShuiZhu-M08": "方正水柱_GBK",
  "FZShuiZhu-M08S": "方正水柱简体",
  "FZShuiZhu-M08T": "方正水柱繁体",
  "FZSong III-Z05": "方正宋三_GBK",
  "FZSong III-Z05S": "方正宋三简体",
  "FZSongHei-B07": "方正宋黑_GBK",
  "FZSongHei-B07S": "方正宋黑简体",
  "FZSongHei-B07T": "方正宋黑繁体",
  "FZSongYi-Z13S": "方正宋一简体",
  "FZSongYi-Z13T": "方正宋一繁体",
  "FZTJLSFW--GB1-0": "方正铁筋隶书繁体",
  "FZTJLSJW--GB1-0": "方正铁筋隶书简体",
  "FZTieJinLiShu-S17S": "方正铁筋隶书简体",
  "FZTieJinLiShu-Z14T": "方正铁筋隶书繁体",
  "FZWBFW--GB1-0": "方正魏碑繁体",
  "FZWBJW--GB1-0": "方正魏碑简体",
  "FZWBK--GBK1-0": "方正魏碑_GBK",
  "FZWeiBei-S03": "方正魏碑_GBK",
  "FZWeiBei-S03S": "方正魏碑简体",
  "FZWeiBei-S03T": "方正魏碑繁体",
  "FZXBSFW--GB1-0": "方正小标宋繁体",
  "FZXBSJW--GB1-0": "方正小标宋简体",
  "FZXDXJW--GB1-0": "方正细等线简体",
  "FZXDXK--GBK1-0": "方正细等线_GBK",
  "FZXH1FW--GB1-0": "方正细黑一繁体",
  "FZXH1JW--GB1-0": "方正细黑一简体",
  "FZXIANGLFW--GB1-0": "方正祥隶繁体",
  "FZXIANGLJW--GB1-0": "方正祥隶简体",
  "FZXKFW--GB1-0": "方正行楷繁体",
  "FZXKJW--GB1-0": "方正行楷简体",
  "FZXKK--GBK1-0": "方正行楷_GBK",
  "FZXLFW--GB1-0": "方正报宋繁体",
  "FZXQFW--GB1-0": "方正细倩繁体",
  "FZXQJW--GB1-0": "方正细倩简体",
  "FZXQK--GBK1-0": "方正细倩_GBK",
  "FZXSHFW--GB1-0": "方正细珊瑚繁体",
  "FZXSHJW--GB1-0": "方正细珊瑚简体",
  "FZXSHK--GBK1-0": "方正细珊瑚_GBK",
  "FZXSSFW--GB1-0": "方正新书宋繁体",
  "FZXXLFW--GB1-0": "方正新秀丽繁体",
  "FZXZTFW--GB1-0": "方正小篆体",
  "FZXiDengXian-Z06": "方正细等线_GBK",
  "FZXiDengXian-Z06S": "方正细等线简体",
  "FZXiHei I-Z08S": "方正细黑一简体",
  "FZXiHei I-Z08T": "方正细黑一繁体",
  "FZXiQian-M15": "方正细倩_GBK",
  "FZXiQian-M15S": "方正细倩简体",
  "FZXiQian-M15T": "方正细倩繁体",
  "FZXiShanHu-M13": "方正细珊瑚_GBK",
  "FZXiShanHu-M13S": "方正细珊瑚简体",
  "FZXiShanHu-M13T": "方正细珊瑚繁体",
  "FZXiYuan-M01S": "方正细圆简体",
  "FZXiYuan-M01T": "方正细圆繁体",
  "FZXiangLi-S17S": "方正祥隶简体",
  "FZXiangLi-S17T": "方正祥隶繁体",
  "FZXiaoBiaoSong-B05S": "方正小标宋简体",
  "FZXiaoBiaoSong-B05T": "方正小标宋繁体",
  "FZXiaoZhuanTi-S13T": "方正小篆体",
  "FZXingKai-S04": "方正行楷_GBK",
  "FZXingKai-S04S": "方正行楷简体",
  "FZXingKai-S04T": "方正行楷繁体",
  "FZY1FW--GB1-0": "方正细圆繁体",
  "FZY1JW--GB1-0": "方正细圆简体",
  "FZY3FW--GB1-0": "方正准圆繁体",
  "FZY3JW--GB1-0": "方正准圆简体",
  "FZY3K--GBK1-0": "方正准圆_GBK",
  "FZY4FW--GB1-0": "方正粗圆繁体",
  "FZY4JW--GB1-0": "方正粗圆简体",
  "FZY4K--GBK1-0": "方正粗圆_GBK",
  "FZYBKSFW--GB1-0": "方正硬笔楷书繁体",
  "FZYBKSJW--GB1-0": "方正硬笔楷书简体",
  "FZYBXSFW--GB1-0": "方正硬笔行书繁体",
  "FZYBXSJW--GB1-0": "方正硬笔行书简体",
  "FZYHFW--GB1-0": "方正艺黑繁体",
  "FZYHJW--GB1-0": "方正艺黑简体",
  "FZYTFW--GB1-0": "方正姚体繁体",
  "FZYTJW--GB1-0": "方正姚体简体",
  "FZYTK--GBK1-0": "方正姚体_GBK",
  "FZYXFW--GB1-0": "方正幼线繁体",
  "FZYXJW--GB1-0": "方正幼线简体",
  "FZYXK--GBK1-0": "方正幼线_GBK",
  "FZYaSong-EB-GBK": "方正大雅宋_GBK",
  "FZYaoTi-M06": "方正姚体_GBK",
  "FZYaoTi-M06S": "方正姚体简体",
  "FZYaoTi-M06T": "方正姚体繁体",
  "FZYiHei-M20S": "方正艺黑简体",
  "FZYiHei-M20T": "方正艺黑繁体",
  "FZYingBiKaiShu-S15S": "方正硬笔楷书简体",
  "FZYingBiKaiShu-S15T": "方正硬笔楷书繁体",
  "FZYingBiXingShu-S16S": "方正硬笔行书简体",
  "FZYingBiXingShu-S16T": "方正硬笔行书繁体",
  "FZYouXian-Z09": "方正幼线_GBK",
  "FZYouXian-Z09S": "方正幼线简体",
  "FZYouXian-Z09T": "方正幼线繁体",
  "FZZBHFW--GB1-0": "方正毡笔黑繁体",
  "FZZBHJW--GB1-0": "方正毡笔黑简体",
  "FZZCHK--GBK1-0": "方正正粗黑_GBK",
  "FZZDXFW--GB1-0": "方正中等线繁体",
  "FZZDXJW--GB1-0": "方正中等线简体",
  "FZZHYFW--GB1-0": "方正稚艺繁体",
  "FZZHYJW--GB1-0": "方正稚艺简体",
  "FZZHYK--GBK1-0": "方正稚艺_GBK",
  "FZZKFW--GB1-0": "方正中楷繁体",
  "FZZQFW--GB1-0": "方正中倩繁体",
  "FZZQJW--GB1-0": "方正中倩简体",
  "FZZQK--GBK1-0": "方正中倩_GBK",
  "FZZYFW--GB1-0": "方正综艺繁体",
  "FZZYJW--GB1-0": "方正综艺简体",
  "FZZYK--GBK1-0": "方正综艺_GBK",
  "FZZhanBiHei-M22S": "方正毡笔黑简体",
  "FZZhanBiHei-M22T": "方正毡笔黑繁体",
  "FZZhengHei-B-GBK": "方正正粗黑_GBK",
  "FZZhiYi-M12": "方正稚艺_GBK",
  "FZZhiYi-M12S": "方正稚艺简体",
  "FZZhiYi-M12T": "方正稚艺繁体",
  "FZZhongDengXian-Z07S": "方正中等线简体",
  "FZZhongDengXian-Z07T": "方正中等线繁体",
  "FZZhongKai-B08T": "方正中楷繁体",
  "FZZhongQian-M16": "方正中倩_GBK",
  "FZZhongQian-M16S": "方正中倩简体",
  "FZZhongQian-M16T": "方正中倩繁体",
  "FZZhunYuan-M02": "方正准圆_GBK",
  "FZZhunYuan-M02S": "方正准圆简体",
  "FZZhunYuan-M02T": "方正准圆繁体",
  "FZZongYi-M05": "方正综艺_GBK",
  "FZZongYi-M05S": "方正综艺简体",
  "FZZongYi-M05T": "方正综艺繁体",
  "FZuanSu": "迷你繁篆书",
  "FangSong": "仿宋",
  "FangSong_GB2312": "仿宋_GB2312",
  "Fashion font,  by www.6763.net": "时装歪歪体《做字网》定做下载...",
  "Fashion font, by www.6763.NET": "时装字中字,《做字网》定做下载..",
  "Fashion font, by www.6763.net": "时装歪歪体《做字网》定做下载...",
  "Fashion font, made by www.6763.": "时装扭动体,《做字网》定做下载..",
  "Fashion font, made by www.6763.net": "时装扭动体,《做字网》定做下载..",
  "Fcaili": "迷你繁曹隶",
  "Fheifangbei": "迷你繁衡方碑",
  "Fliukai": "迷你繁柳楷",
  "Fluxing": "迷你繁陆行",
  "Font Sistem": "系统字体",
  "Font Sistem Italik Biasa": "系统字体",
  "Font Sistem Reguler Cetak Miring": "系统字体",
  "Font de sistem": "系统字体",
  "Font de sistem Normal cursiv": "系统字体",
  "Font di sistema": "系统字体",
  "Font di sistema Regolare corsivo": "系统字体",
  "Font sustava": "系统字体",
  "Font sustava Regular Italic": "系统字体",
  "Fonte do Sistema": "系统字体",
  "Fonte do Sistema Normal Itálico": "系统字体",
  "Fouxing": "迷你繁欧行",
  "Ftangli": "迷你繁唐隶",
  "Fzicao": "迷你繁智草",
  "Fzikai": "迷你繁智楷",
  "GJJCQJW--GB1-0": "迷你简粗倩",
  "GJJCuQian-M17S": "迷你简粗倩",
  "GJJHCJW--GB1-0": "迷你简黄草",
  "GJJHPJW--GB1-0": "迷你简琥珀",
  "GJJHuangCao-S09S": "迷你简黄草",
  "GJJSZJW--GB1-0": "迷你简水柱",
  "GJJShuiZhu-M08S": "迷你简水柱",
  "GJJXQJW--GB1-0": "迷你简细倩",
  "GJJXiQian-M15S": "迷你简细倩",
  "GJJZHYJW--GB1-0": "迷你简稚艺",
  "GJJZQJW--GB1-0": "迷你简中倩",
  "GJJZhiYi-M12S": "迷你简稚艺",
  "GJJZhongQian-M16S": "迷你简中倩",
  "Gen Jyuu Gothic": "源柔ゴシック Regular",
  "Gen Jyuu Gothic Regular": "源柔ゴシック Regular",
  "GenJyuuGothic-Regular": "源柔ゴシック Regular",
  "HYBaiQiJ": "汉仪白棋体简",
  "HYBaoSongF": "汉仪报宋繁",
  "HYBaoSongJ": "汉仪报宋简",
  "HYCaiDieJ": "汉仪彩蝶体简",
  "HYCaiYunF": "汉仪彩云体繁",
  "HYCaiYunJ": "汉仪彩云体简",
  "HYChangMeiHeiF": "汉仪长美黑繁",
  "HYChangMeiHeiJ": "汉仪长美黑简",
  "HYChangSongF": "汉仪长宋繁",
  "HYChangSongJ": "汉仪长宋简",
  "HYChangYiF": "汉仪长艺体繁",
  "HYChangYiJ": "汉仪长艺体简",
  "HYChaoCuHeiF": "汉仪超粗黑繁",
  "HYChaoCuHeiJ": "汉仪超粗黑简",
  "HYChaoCuSongF": "汉仪超粗宋繁",
  "HYChaoCuSongJ": "汉仪超粗宋简",
  "HYChaoCuYuanJ": "汉仪超粗圆简",
  "HYChenPinJ": "汉仪陈频破体简",
  "HYCuFangSongJ": "汉仪粗仿宋简",
  "HYCuHeiF": "汉仪粗黑繁",
  "HYCuHeiJ": "汉仪粗黑简",
  "HYCuSongF": "汉仪粗宋繁",
  "HYCuSongJ": "汉仪粗宋简",
  "HYCuYuanF": "汉仪粗圆繁",
  "HYCuYuanJ": "汉仪粗圆简",
  "HYCuZhuanF": "汉仪粗篆繁",
  "HYDaHeiF": "汉仪大黑繁",
  "HYDaHeiJ": "汉仪大黑简",
  "HYDaLiShuF": "汉仪大隶书繁",
  "HYDaLiShuJ": "汉仪大隶书简",
  "HYDaSongF": "汉仪大宋繁",
  "HYDaSongJ": "汉仪大宋简",
  "HYDaiYuJ": "汉仪黛玉体简",
  "HYDieYuJ": "汉仪蝶语体简",
  "HYDuDuJ": "汉仪嘟嘟体简",
  "HYFangDieF": "汉仪方叠体繁",
  "HYFangDieJ": "汉仪方叠体简",
  "HYFangLiJ": "汉仪方隶简",
  "HYFangSongF": "汉仪仿宋繁",
  "HYFangSongJ": "汉仪仿宋简",
  "HYGanLanF": "汉仪橄榄体繁",
  "HYGanLanJ": "汉仪橄榄体简",
  "HYHaHaJ": "汉仪哈哈体简",
  "HYHaiYunJ": "汉仪海韵体简",
  "HYHeiMiF": "汉仪黑咪体繁",
  "HYHeiMiJ": "汉仪黑咪体简",
  "HYHeiQiJ": "汉仪黑棋体简",
  "HYHuPoF": "汉仪琥珀体繁",
  "HYHuPoJ": "汉仪琥珀体简",
  "HYHuaDieJ": "汉仪花蝶体简",
  "HYHuoChaiJ": "汉仪火柴体简",
  "HYJiaShuF": "汉仪家书繁",
  "HYJiaShuJ": "汉仪家书简",
  "HYKaiTiF": "汉仪楷体繁",
  "HYKaiTiJ": "汉仪楷体简",
  "HYLiHeiJ": "汉仪立黑简",
  "HYLingBoF": "汉仪凌波体繁",
  "HYLingBoJ": "汉仪凌波体简",
  "HYLingXinJ": "汉仪菱心体简",
  "HYLuoBoJ": "汉仪萝卜体简",
  "HYManBuF": "汉仪漫步体繁",
  "HYManBuJ": "汉仪漫步体简",
  "HYMiMiF": "汉仪咪咪体繁",
  "HYMiMiJ": "汉仪咪咪体简",
  "HYNanGongJ": "汉仪南宫体简",
  "HYQingYunJ": "汉仪清韵体简",
  "HYShenGongJ": "汉仪神工体简",
  "HYShouJinShuF": "汉仪瘦金书繁",
  "HYShouJinShuJ": "汉仪瘦金书简",
  "HYShuHunJ": "汉仪书魂体简",
  "HYShuSongErF": "汉仪书宋二繁",
  "HYShuSongErJ": "汉仪书宋二简",
  "HYShuSongYiF": "汉仪书宋一繁",
  "HYShuSongYiJ": "汉仪书宋一简",
  "HYShuTongF": "汉仪舒同体繁",
  "HYShuTongJ": "汉仪舒同体简",
  "HYShuangXianF": "汉仪双线体繁",
  "HYShuangXianJ": "汉仪双线体简",
  "HYShuiBoJ": "汉仪水波体简",
  "HYShuiDiF": "汉仪水滴体繁",
  "HYShuiDiJ": "汉仪水滴体简",
  "HYTaiJiJ": "汉仪太极体简",
  "HYTeXiDengXianJ": "汉仪特细等线简",
  "HYWaWaZhuanJ": "汉仪娃娃篆简",
  "HYWeiBeiF": "汉仪魏碑繁",
  "HYWeiBeiJ": "汉仪魏碑简",
  "HYXiDengXianF": "汉仪细等线繁",
  "HYXiDengXianJ": "汉仪细等线简",
  "HYXiXingKaiJ": "汉仪细行楷简",
  "HYXiYuanF": "汉仪细圆繁",
  "HYXiYuanJ": "汉仪细圆简",
  "HYXiZhongYuanF": "汉仪细中圆繁",
  "HYXiZhongYuanJ": "汉仪细中圆简",
  "HYXiaoLiShuF": "汉仪小隶书繁",
  "HYXiaoLiShuJ": "汉仪小隶书简",
  "HYXingKaiF": "汉仪行楷繁",
  "HYXingKaiJ": "汉仪行楷简",
  "HYXingShiF": "汉仪醒示体繁",
  "HYXingShiJ": "汉仪醒示体简",
  "HYXiuYingF": "汉仪秀英体繁",
  "HYXiuYingJ": "汉仪秀英体简",
  "HYXueFengF": "汉仪雪峰体繁",
  "HYXueFengJ": "汉仪雪峰体简",
  "HYYaYaJ": "汉仪丫丫体简",
  "HYYanKaiF": "汉仪颜楷繁",
  "HYYanLingJ": "汉仪雁翎体简",
  "HYYuanDieF": "汉仪圆叠体繁",
  "HYYuanDieJ": "汉仪圆叠体简",
  "HYZHongSongJ": "汉仪中宋简",
  "HYZhongDengXianF": "汉仪中等线繁",
  "HYZhongDengXianJ": "汉仪中等线简",
  "HYZhongHeiF": "汉仪中黑繁",
  "HYZhongHeiJ": "汉仪中黑简",
  "HYZhongKaiJ": "汉仪中楷简",
  "HYZhongLiShuF": "汉仪中隶书繁",
  "HYZhongLiShuJ": "汉仪中隶书简",
  "HYZhongSongF": "汉仪中宋繁",
  "HYZhongYuanF": "汉仪中圆繁",
  "HYZhongYuanJ": "汉仪中圆简",
  "HYZhuJieF": "汉仪竹节体繁",
  "HYZhuJieJ": "汉仪竹节体简",
  "HYZhuanShuF": "汉仪篆书繁",
  "HYZiDianSongF": "汉仪字典宋繁",
  "HYZiDianSongJ": "汉仪字典宋简",
  "HYZongYiF": "汉仪综艺体繁",
  "HYZongYiJ": "汉仪综艺体简",
  "HYa0gf": "汉仪超粗宋繁",
  "HYa0gj": "汉仪超粗宋简",
  "HYa1gf": "汉仪书宋一繁",
  "HYa1gj": "汉仪书宋一简",
  "HYa2gf": "汉仪报宋繁",
  "HYa2gj": "汉仪报宋简",
  "HYa3gf": "汉仪中宋繁",
  "HYa3gj": "汉仪中宋简",
  "HYa4gf": "汉仪大宋繁",
  "HYa4gj": "汉仪大宋简",
  "HYa5gf": "汉仪长宋繁",
  "HYa5gj": "汉仪长宋简",
  "HYa6gf": "汉仪书宋二繁",
  "HYa6gj": "汉仪书宋二简",
  "HYa7gf": "汉仪字典宋繁",
  "HYa7gj": "汉仪字典宋简",
  "HYa9gf": "汉仪粗宋繁",
  "HYa9gj": "汉仪粗宋简",
  "HYb0gf": "汉仪超粗黑繁",
  "HYb0gj": "汉仪超粗黑简",
  "HYb1gf": "汉仪中黑繁",
  "HYb1gj": "汉仪中黑简",
  "HYb2gf": "汉仪大黑繁",
  "HYb2gj": "汉仪大黑简",
  "HYb3gf": "汉仪长美黑繁",
  "HYb3gj": "汉仪长美黑简",
  "HYb4gf": "汉仪方叠体繁",
  "HYb4gj": "汉仪方叠体简",
  "HYb5gf": "汉仪醒示体繁",
  "HYb5gj": "汉仪醒示体简",
  "HYb6gf": "汉仪长艺体繁",
  "HYb6gj": "汉仪长艺体简",
  "HYb7gf": "汉仪双线体繁",
  "HYb7gj": "汉仪双线体简",
  "HYb8gf": "汉仪圆叠体繁",
  "HYb8gj": "汉仪圆叠体简",
  "HYb9gf": "汉仪粗黑繁",
  "HYb9gj": "汉仪粗黑简",
  "HYc1gf": "汉仪楷体繁",
  "HYc1gj": "汉仪楷体简",
  "HYc3gj": "汉仪中楷简",
  "HYc4gf": "迷你繁赵楷",
  "HYd1gf": "汉仪仿宋繁",
  "HYd1gj": "汉仪仿宋简",
  "HYd2gf": "汉仪家书繁",
  "HYd2gj": "汉仪家书简",
  "HYd4gj": "汉仪粗仿宋简",
  "HYe0gj": "汉仪超粗圆简",
  "HYe1gf": "汉仪细圆繁",
  "HYe1gj": "汉仪细圆简",
  "HYe2gf": "汉仪细中圆繁",
  "HYe2gj": "汉仪细中圆简",
  "HYe3gf": "汉仪中圆繁",
  "HYe3gj": "汉仪中圆简",
  "HYe4gf": "汉仪粗圆繁",
  "HYe4gj": "汉仪粗圆简",
  "HYf0gj": "汉仪方隶简",
  "HYf1gf": "汉仪大隶书繁",
  "HYf1gj": "汉仪大隶书简",
  "HYf2gf": "汉仪小隶书繁",
  "HYf2gj": "汉仪小隶书简",
  "HYf3gf": "汉仪中隶书繁",
  "HYf3gj": "汉仪中隶书简",
  "HYf4gj": "汉仪雁翎体简",
  "HYf5gj": "汉仪陈频破体简",
  "HYf9gj": "迷你简花蝶",
  "HYg1gf": "汉仪细等线繁",
  "HYg1gj": "汉仪细等线简",
  "HYg2gf": "汉仪中等线繁",
  "HYg2gj": "汉仪中等线简",
  "HYg3gj": "汉仪丫丫体简",
  "HYg4gj": "迷你简清韵",
  "HYg6gj": "汉仪特细等线简",
  "HYh1gf": "汉仪魏碑繁",
  "HYh1gj": "汉仪魏碑简",
  "HYh2gj": "汉仪神工体简",
  "HYh3gj": "汉仪书魂体简",
  "HYh4gj": "汉仪南宫体简",
  "HYi1gf": "汉仪行楷繁",
  "HYi1gj": "汉仪行楷简",
  "HYi2gj": "汉仪细行楷简",
  "HYi3gf": "汉仪瘦金书繁",
  "HYi3gj": "汉仪瘦金书简",
  "HYi4gj": "迷你简雪君",
  "HYj1gf": "汉仪篆书繁",
  "HYj2gj": "汉仪娃娃篆简",
  "HYj3gf": "汉仪粗篆繁",
  "HYk1gf": "汉仪综艺体繁",
  "HYk1gj": "汉仪综艺体简",
  "HYk2gj": "汉仪菱心体简",
  "HYk3gj": "迷你简海韵",
  "HYk5gj": "迷你简彩蝶",
  "HYl1gf": "汉仪彩云体繁",
  "HYl1gj": "汉仪彩云体简",
  "HYm1gf": "汉仪咪咪体繁",
  "HYm1gj": "汉仪咪咪体简",
  "HYm2gf": "汉仪黑咪体繁",
  "HYm2gj": "汉仪黑咪体简",
  "HYm4gj": "汉仪哈哈体简",
  "HYm5gj": "汉仪白棋体简",
  "HYm6gj": "汉仪黑棋体简",
  "HYm7gj": "迷你简水波",
  "HYn1gf": "汉仪舒同体繁",
  "HYn1gj": "汉仪舒同体简",
  "HYn3gj": "迷你简蝶语",
  "HYo1gf": "汉仪琥珀体繁",
  "HYo1gj": "汉仪琥珀体简",
  "HYo2gf": "汉仪雪峰体繁",
  "HYo2gj": "汉仪雪峰体简",
  "HYo3gj": "汉仪太极体简",
  "HYp1gf": "汉仪水滴体繁",
  "HYp1gj": "迷你简水滴",
  "HYq1gf": "汉仪竹节体繁",
  "HYq1gj": "汉仪竹节体简",
  "HYq2gj": "汉仪火柴体简",
  "HYr1gf": "汉仪凌波体繁",
  "HYr1gj": "汉仪凌波体简",
  "HYr2gf": "汉仪漫步体繁",
  "HYr2gj": "汉仪漫步体简",
  "HYr3gj": "汉仪黛玉体简",
  "HYt4gj": "汉仪立黑简",
  "HYx1gf": "汉仪橄榄体繁",
  "HYx1gj": "汉仪橄榄体简",
  "HYx4gf": "汉仪颜楷繁",
  "HYy1gf": "汉仪秀英体繁",
  "HYy1gj": "汉仪秀英体简",
  "HYy2gj": "汉仪萝卜体简",
  "HYy4gj": "汉仪嘟嘟体简",
  "HakusyuGyosyoPro_kk": "白舟行書Pro教漢",
  "HakusyuGyosyo_kk": "白舟行書教漢",
  "HakusyuInsoutai_kk": "白舟印相体教漢",
  "HanWangCC02": "王漢宗酷儷海報",
  "HanWangFangSongMedium": "王漢宗中仿宋繁",
  "HanWangFangSongMedium-Gb5": "王汉宗中仿宋简",
  "HanWangGB06": "王漢宗鋼筆行楷繁",
  "HanWangGSolid06cut1": "王漢宗超黑體俏皮動物一",
  "HanWangHeiHeavy": "王漢宗特黑體繁",
  "HanWangKaiBold-Gb5": "王汉宗粗楷体简",
  "HanWangKaiMediumChuIn": "王漢宗中楷體注音",
  "HanWangKanTan": "王漢宗勘亭流繁",
  "HanWangMingBlack": "王漢宗超明體繁",
  "HanWangMingHeavy": "王漢宗特明體繁",
  "HanWangMingMedium": "王漢宗中明體繁",
  "HanWangMingMediumPoIn2": "王漢宗中明體破音二",
  "HanWangMingMediumPoIn3": "王漢宗中明體破音三",
  "HanWangSinSongThin-Gb5": "王汉宗细新宋简",
  "HanWangWCL02": "王漢宗特明體一標準",
  "HanWangWCL03": "王漢宗波卡體一空陰",
  "HanWangWCL05": "王漢宗標楷體一空心",
  "HanWangWCL06": "王漢宗仿宋體一標準",
  "HanWangWCL08": "王漢宗粗黑體一實陰",
  "HanWangWCL10": "王漢宗海報體一半天水",
  "HanWangYenHeavy": "王漢宗特圓體繁",
  "Heiti TC": "黑体-繁",
  "Heiti TC Light": "黑体-繁",
  "Heiti TC Medium": "黑体-繁",
  "Heiti-번체": "黑体-繁",
  "Heiti-번체 가는체": "黑体-繁",
  "Heiti-번체 중간체": "黑体-繁",
  "HiraMaruPro-W4": "ヒラギノ丸ゴ Pro",
  "HiraMinProN-W3": "ヒラギノ明朝 ProN",
  "Hiragino Maru Gothic Pro": "ヒラギノ丸ゴ Pro",
  "Hiragino Maru Gothic Pro W4": "ヒラギノ丸ゴ Pro",
  "Hiragino Mincho ProN": "ヒラギノ明朝 ProN",
  "Hiragino Mincho ProN W3": "ヒラギノ明朝 ProN",
  "Hiragino Sans": "ヒラギノ角ゴシック",
  "Hiragino Sans GB": "冬青黑体简体中文 W3",
  "Hiragino Sans GB W3": "冬青黑体简体中文 W3",
  "Hiragino Sans W0": "ヒラギノ角ゴシック",
  "Hiragino Sans W1": "ヒラギノ角ゴシック",
  "Hiragino Sans W2": "ヒラギノ角ゴシック",
  "Hiragino Sans W3": "ヒラギノ角ゴシック",
  "Hiragino Sans W4": "ヒラギノ角ゴシック",
  "Hiragino Sans W5": "ヒラギノ角ゴシック",
  "Hiragino Sans W6": "ヒラギノ角ゴシック",
  "Hiragino Sans W7": "ヒラギノ角ゴシック",
  "Hiragino Sans W8": "ヒラギノ角ゴシック",
  "Hiragino Sans W9": "ヒラギノ角ゴシック",
  "HiraginoSans-W0": "ヒラギノ角ゴシック",
  "HiraginoSans-W1": "ヒラギノ角ゴシック",
  "HiraginoSans-W2": "ヒラギノ角ゴシック",
  "HiraginoSans-W3": "ヒラギノ角ゴシック",
  "HiraginoSans-W4": "ヒラギノ角ゴシック",
  "HiraginoSans-W5": "ヒラギノ角ゴシック",
  "HiraginoSans-W6": "ヒラギノ角ゴシック",
  "HiraginoSans-W7": "ヒラギノ角ゴシック",
  "HiraginoSans-W8": "ヒラギノ角ゴシック",
  "HiraginoSans-W9": "ヒラギノ角ゴシック",
  "HiraginoSansGB-W3": "冬青黑体简体中文 W3",
  "JCaoCuYuan": "迷你简超粗圆",
  "JChangYi": "迷你简长艺",
  "JChenPinPo": "迷你简陈频破",
  "JCuYuan": "迷你简粗圆",
  "JDaiYu": "迷你简黛玉",
  "JDuDu": "迷你简嘟嘟体",
  "JFangLi": "迷你简方隶",
  "JHaHa": "迷你简哈哈",
  "JHuaLi": "迷你简华隶",
  "JHuoCai": "迷你简火柴",
  "JKangTi": "迷你简康体",
  "JLiBian": "迷你简隶变",
  "JLiEr": "迷你简隶二",
  "JLiHei": "迷你简立黑",
  "JLinBo": "迷你简凌波",
  "JLuobo": "迷你简萝卜",
  "JManBuTi": "迷你简漫步",
  "JMeiHei": "迷你简美黑",
  "JPangWa": "迷你简胖娃",
  "JPinHe": "迷你简平和",
  "JSaoEr": "迷你简少儿",
  "JShuShong": "迷你简书宋",
  "JShuTi": "迷你简舒体",
  "JSouJingSu": "迷你简瘦金书",
  "JTeXiDenXian": "迷你简特细等线",
  "JWaWAZuan": "迷你简娃娃篆",
  "JXiHei": "迷你简细黑",
  "JXiSanHu": "迷你简细珊瑚",
  "JXiaoLiSu": "迷你简小隶书",
  "JXinBaoSong": "迷你简新报宋",
  "JXinSuTi": "迷你简新舒体",
  "JXiuYing": "迷你简秀英",
  "JXueFeng": "迷你简雪峰",
  "JYaYa": "迷你简丫丫",
  "JYanLin": "迷你简雁翎",
  "JYaoTi": "迷你简姚体",
  "JZhiDianSong": "迷你简字典宋",
  "JZuJie": "迷你简竹节",
  "JZunYuan": "迷你简准圆",
  "Jcacuhei": "迷你简超粗黑",
  "Jcufangsong": "迷你简粗仿宋",
  "Jheiqi": "迷你简黑棋",
  "Jquwei": "迷你简趣味",
  "Jtaiji": "迷你简太极",
  "Järjestelmäfontti": "系统字体",
  "Järjestelmäfontti Normaali kursiivi": "系统字体",
  "KaiTi": "楷体",
  "MINIJbaiqi": "迷你简白棋",
  "MINIj4gj": "迷你简柏青",
  "MKsoTouryu": "A_KSO 闘龍",
  "Malgun Gothic": "맑은 고딕 Semilight",
  "Malgun Gothic Bold": "맑은 고딕",
  "Malgun Gothic Semilight": "맑은 고딕 Semilight",
  "MalgunGothic": "맑은 고딕",
  "MalgunGothic-Semilight": "맑은 고딕 Semilight",
  "MalgunGothicBold": "맑은 고딕",
  "NanSung-Medium": "超研澤中仿",
  "Phông chữ Hệ thống": "系统字体",
  "Phông chữ Hệ thống Nghiêng Thường": "系统字体",
  "Police système": "系统字体",
  "Police système Courant italique": "系统字体",
  "Rendszerbetűtípus": "系统字体",
  "Rendszerbetűtípus Normál dőlt": "系统字体",
  "RiWenMaoBiXingShu": "★日文毛笔行书",
  "SCF-9jiangxs": "书体坊赵九江钢笔行书",
  "STHeitiTC-Light": "黑体-繁",
  "STHeitiTC-Medium": "黑体-繁",
  "STSongti-SC-Black": "宋体-简",
  "SimHei": "黑体",
  "SimSun": "宋体",
  "Sistem Fontu": "系统字体",
  "Sistem Fontu Normal İtalik": "系统字体",
  "Songti SC": "宋体-简",
  "Songti SC Black": "宋体-简",
  "Source Han Sans CN": "思源黑体 CN Medium",
  "Source Han Sans CN Medium": "思源黑体 CN Medium",
  "Source Han Sans JP": "源ノ角ゴシック JP Medium",
  "Source Han Sans JP Medium": "源ノ角ゴシック JP Medium",
  "Source Han Sans SC": "思源黑体",
  "Source Han Sans TW": "思源黑體 TW Medium",
  "Source Han Sans TW Medium": "思源黑體 TW Medium",
  "SourceHanSansCN-Medium": "思源黑体 CN Medium",
  "SourceHanSansJP-Medium": "源ノ角ゴシック JP Medium",
  "SourceHanSansSC-Regular": "思源黑体",
  "SourceHanSansTW-Medium": "思源黑體 TW Medium",
  "Systeemlettertype": "系统字体",
  "Systeemlettertype Regulier cursief": "系统字体",
  "System Font": "系统字体",
  "System Font Regular Italic": "系统字体",
  "Systemfont": "系统字体",
  "Systemfont Normal kursiv": "系统字体",
  "Systemschrift": "系统字体",
  "Systemschrift Regular kursiv": "系统字体",
  "Systemskrift": "系统字体",
  "Systemskrift Normal kursiv": "系统字体",
  "Systemtypsnitt": "系统字体",
  "Systemtypsnitt Normal kursiv": "系统字体",
  "Systémové písmo": "系统字体",
  "Systémové písmo Regular Italic": "系统字体",
  "Tipo de letra del sistema": "系统字体",
  "Tipo de letra del sistema Cursiva regular": "系统字体",
  "Tipo de letra do sistema": "系统字体",
  "Tipo de letra do sistema Regular itálico": "系统字体",
  "Tipus de lletra del sistema": "系统字体",
  "Tipus de lletra del sistema Normal cursiva": "系统字体",
  "WenQuanYi Micro Hei": "文泉驿微米黑",
  "WenQuanYi Micro Hei Mono": "文泉驿等宽微米黑",
  "WenQuanYi Zen Hei": "文泉驿正黑",
  "WenQuanYi Zen Hei Mono": "文泉驿等宽正黑",
  "WenQuanYiMicroHei": "文泉驿微米黑",
  "WenQuanYiMicroHeiMono": "文泉驿等宽微米黑",
  "WenQuanYiZenHei": "文泉驿正黑",
  "WenQuanYiZenHeiMono": "文泉驿等宽正黑",
  "fwangxing": "迷你繁王行",
  "fzukai": "迷你繁褚楷",
  "not included.": "叶根友非主流手",
  "システムフォント": "系统字体",
  "システムフォント レギュラー・イタリック": "系统字体",
  "ヒラギノ丸ゴ Pro W4": "ヒラギノ丸ゴ Pro",
  "ヒラギノ明朝 ProN W3": "ヒラギノ明朝 ProN",
  "ヒラギノ角ゴシック Sans W8": "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック W0": "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック W1": "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック W2": "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック W3": "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック W4": "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック W5": "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック W6": "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック W7": "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック W8": "ヒラギノ角ゴシック",
  "ヒラギノ角ゴシック W9": "ヒラギノ角ゴシック",
  "冬青黑体简体中文": "冬青黑体简体中文 W3",
  "冬青黑體簡體中文": "冬青黑体简体中文 W3",
  "冬青黑體簡體中文 W3": "冬青黑体简体中文 W3",
  "宋体-简 黑体": "宋体-简",
  "宋體-簡": "宋体-简",
  "宋體-簡 黑體": "宋体-简",
  "帅Fashion font, made by www.6763.net": "时装褶皱体,《做字网》定做下载..",
  "广捷居迷你字库": "迷你简汉真广标",
  "思源黑体 CN": "思源黑体 CN Medium",
  "思源黑體 TW": "思源黑體 TW Medium",
  "文泉驛微米黑": "文泉驿微米黑",
  "文泉驛正黑": "文泉驿正黑",
  "文泉驛等寬微米黑": "文泉驿等宽微米黑",
  "文泉驛等寬正黑": "文泉驿等宽正黑",
  "时装三维体,《做字网》定做下载....": "时装三维体,《做字网》定做下载..",
  "时装分块体,《做字网》定做下载....": "时装分块体,《做字网》定做下载..",
  "时装字中字,《做字网》定做下载....": "时装字中字,《做字网》定做下载..",
  "时装小立体,《做字网》定做下载....": "时装小立体,《做字网》定做下载..",
  "时装扭动体,《做字网》定做下载....": "时装扭动体,《做字网》定做下载..",
  "时装扭曲体,《做字网》定做下载....": "时装扭曲体,《做字网》定做下载..",
  "时装描边体,《做字网》定做下载....": "时装描边体,《做字网》定做下载..",
  "时装揪心体,《做字网》定做下载....": "时装揪心体,《做字网》定做下载..",
  "时装斑马魏《做字网》更多下载....": "时装斑马魏《做字网》更多下载...",
  "时装歪歪体《做字网》定做下载....": "时装歪歪体《做字网》定做下载...",
  "时装残破体《做字网》定做下载....": "时装残破体《做字网》定做下载...",
  "时装滚边体,《做字网》定做下载....": "时装滚边体,《做字网》定做下载..",
  "时装碎石体《做字网》定做下载....": "时装碎石体《做字网》定做下载...",
  "时装空心体,《做字网》定做下载....": "时装空心体,《做字网》定做下载..",
  "时装虫蚀体《做字网》定做下载....": "时装虫蚀体《做字网》定做下载...",
  "时装蚂蚁体,《做字网》定做下载....": "时装蚂蚁体,《做字网》定做下载..",
  "时装蟒纹体《做字网》定做下载....": "时装蟒纹体《做字网》定做下载...",
  "时装褶皱体,《做字网》定做下载....": "时装褶皱体,《做字网》定做下载..",
  "源ノ角ゴシック JP": "源ノ角ゴシック JP Medium",
  "源柔ゴシック": "源柔ゴシック Regular",
  "王漢宗中仿宋簡": "王汉宗中仿宋简",
  "王漢宗粗楷體簡": "王汉宗粗楷体简",
  "王漢宗細新宋簡": "王汉宗细新宋简",
  "等线": "等线 Light",
  "等线 Bold": "等线",
  "系統字體": "系统字体",
  "系統字體 標準斜體": "系统字体",
  "系统字体 常规斜体": "系统字体",
  "迷你简楷体_GB2312": "迷你简楷体",
  "黑体-繁 中等": "黑体-繁",
  "黑体-繁 细体": "黑体-繁",
  "黑體-繁": "黑体-繁",
  "黑體-繁 中黑": "黑体-繁",
  "黑體-繁 細體": "黑体-繁",
  "黒体-繁": "黑体-繁",
  "黒体-繁 ミディアム": "黑体-繁",
  "黒体-繁 ライト": "黑体-繁",
  "맑은 고딕": "맑은 고딕 Semilight",
  "맑은 고딕 Bold": "맑은 고딕",
  "시스템 서체": "系统字体",
  "시스템 서체 일반 이탤릭체": "系统字体",
}
